/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ch.inofix.sketchboard.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SketchBoard service. Represents a row in the &quot;inofix_sb_SketchBoard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ch.inofix.sketchboard.model.impl.SketchBoardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ch.inofix.sketchboard.model.impl.SketchBoardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SketchBoard
 * @see ch.inofix.sketchboard.model.impl.SketchBoardImpl
 * @see ch.inofix.sketchboard.model.impl.SketchBoardModelImpl
 * @generated
 */
@ProviderType
public interface SketchBoardModel extends BaseModel<SketchBoard>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sketch board model instance should use the {@link SketchBoard} interface instead.
	 */

	/**
	 * Returns the primary key of this sketch board.
	 *
	 * @return the primary key of this sketch board
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sketch board.
	 *
	 * @param primaryKey the primary key of this sketch board
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sketch board.
	 *
	 * @return the uuid of this sketch board
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sketch board.
	 *
	 * @param uuid the uuid of this sketch board
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sketch board ID of this sketch board.
	 *
	 * @return the sketch board ID of this sketch board
	 */
	public long getSketchBoardId();

	/**
	 * Sets the sketch board ID of this sketch board.
	 *
	 * @param sketchBoardId the sketch board ID of this sketch board
	 */
	public void setSketchBoardId(long sketchBoardId);

	/**
	 * Returns the group ID of this sketch board.
	 *
	 * @return the group ID of this sketch board
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sketch board.
	 *
	 * @param groupId the group ID of this sketch board
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sketch board.
	 *
	 * @return the company ID of this sketch board
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sketch board.
	 *
	 * @param companyId the company ID of this sketch board
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sketch board.
	 *
	 * @return the user ID of this sketch board
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sketch board.
	 *
	 * @param userId the user ID of this sketch board
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sketch board.
	 *
	 * @return the user uuid of this sketch board
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sketch board.
	 *
	 * @param userUuid the user uuid of this sketch board
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sketch board.
	 *
	 * @return the user name of this sketch board
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sketch board.
	 *
	 * @param userName the user name of this sketch board
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sketch board.
	 *
	 * @return the create date of this sketch board
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sketch board.
	 *
	 * @param createDate the create date of this sketch board
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sketch board.
	 *
	 * @return the modified date of this sketch board
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sketch board.
	 *
	 * @param modifiedDate the modified date of this sketch board
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this sketch board.
	 *
	 * @return the status of this sketch board
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this sketch board.
	 *
	 * @param status the status of this sketch board
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this sketch board.
	 *
	 * @return the status by user ID of this sketch board
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this sketch board.
	 *
	 * @param statusByUserId the status by user ID of this sketch board
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this sketch board.
	 *
	 * @return the status by user uuid of this sketch board
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this sketch board.
	 *
	 * @param statusByUserUuid the status by user uuid of this sketch board
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this sketch board.
	 *
	 * @return the status by user name of this sketch board
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this sketch board.
	 *
	 * @param statusByUserName the status by user name of this sketch board
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this sketch board.
	 *
	 * @return the status date of this sketch board
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this sketch board.
	 *
	 * @param statusDate the status date of this sketch board
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this sketch board.
	 *
	 * @return the name of this sketch board
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sketch board.
	 *
	 * @param name the name of this sketch board
	 */
	public void setName(String name);

	/**
	 * Returns the configuration of this sketch board.
	 *
	 * @return the configuration of this sketch board
	 */
	@AutoEscape
	public String getConfiguration();

	/**
	 * Sets the configuration of this sketch board.
	 *
	 * @param configuration the configuration of this sketch board
	 */
	public void setConfiguration(String configuration);

	/**
	 * Returns the setup of this sketch board.
	 *
	 * @return the setup of this sketch board
	 */
	@AutoEscape
	public String getSetup();

	/**
	 * Sets the setup of this sketch board.
	 *
	 * @param setup the setup of this sketch board
	 */
	public void setSetup(String setup);

	/**
	 * Returns <code>true</code> if this sketch board is approved.
	 *
	 * @return <code>true</code> if this sketch board is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this sketch board is denied.
	 *
	 * @return <code>true</code> if this sketch board is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this sketch board is a draft.
	 *
	 * @return <code>true</code> if this sketch board is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this sketch board is expired.
	 *
	 * @return <code>true</code> if this sketch board is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this sketch board is inactive.
	 *
	 * @return <code>true</code> if this sketch board is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this sketch board is incomplete.
	 *
	 * @return <code>true</code> if this sketch board is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this sketch board is pending.
	 *
	 * @return <code>true</code> if this sketch board is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this sketch board is scheduled.
	 *
	 * @return <code>true</code> if this sketch board is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SketchBoard sketchBoard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SketchBoard> toCacheModel();

	@Override
	public SketchBoard toEscapedModel();

	@Override
	public SketchBoard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}