/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ch.inofix.sketchboard.model.impl;

import aQute.bnd.annotation.ProviderType;

import ch.inofix.sketchboard.model.SketchBoard;
import ch.inofix.sketchboard.service.SketchBoardLocalServiceUtil;

/**
 * The extended model base implementation for the SketchBoard service. Represents a row in the &quot;inofix_sb_SketchBoard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SketchBoardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SketchBoardImpl
 * @see SketchBoard
 * @generated
 */
@ProviderType
public abstract class SketchBoardBaseImpl extends SketchBoardModelImpl
	implements SketchBoard {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sketch board model instance should use the {@link SketchBoard} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SketchBoardLocalServiceUtil.addSketchBoard(this);
		}
		else {
			SketchBoardLocalServiceUtil.updateSketchBoard(this);
		}
	}
}